const STORE = 'finwise-v1';
const CATEGORIES = ['Food & drinks','Shopping','Transport','Bills','Other'];
const INCOME_CATEGORIES = ['Salary','Freelance','Business','Gift','Interest','Other income'];
const COLORS = ['#9dca68','#263f3e','#f0b483','#91b3e2','#b9a7d8','#82c4b9','#e2ca8c','#d58f89','#9ab0a0','#c2c9bf'];
const ICONS = {'Food & drinks':'☕','Shopping':'◈','Transport':'➜','Bills':'▤','Health':'✚','Entertainment':'✦','Home':'⌂','Travel':'✈','Education':'▣','Other':'◌','Salary':'↙','Freelance':'↙','Business':'↙','Gift':'♡','Interest':'↙','Other income':'↙'};
const TIPS = ['A small amount saved regularly can make a big difference.','A budget gives every rupee a direction.','Reviewing your spending is a habit worth keeping.','Save for what matters to you, one step at a time.'];
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const uid = () => (crypto.randomUUID ? crypto.randomUUID() : String(Date.now()+Math.random()));
const localDate = d => {const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const today = () => localDate(new Date());
const monthKey = d => String(d||'').slice(0,7);
const thisMonth = () => today().slice(0,7);
const money = n => '₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0});
const exactMoney = n => '₹'+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const niceDate = d => {let x=new Date(`${d}T12:00:00`);return isNaN(x)?String(d):x.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})};
const parseDate = value => {let s=String(value||'').trim();if(!s)return null;if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);let m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/);if(m){let y=Number(m[3]);if(y<100)y+=2000;let d=new Date(y,Number(m[2])-1,Number(m[1]));return isNaN(d)?null:localDate(d)}let d=new Date(s);return isNaN(d)?null:localDate(d)};
const demoDate = (monthsBack,day) => {let d=new Date();d.setDate(1);d.setMonth(d.getMonth()-monthsBack);d.setDate(day);return localDate(d)};
function starterData(){return {demo:true,transactions:[
  {id:uid(),type:'income',amount:82500,category:'Salary',name:'Monthly salary',date:demoDate(0,2)},
  {id:uid(),type:'expense',amount:18500,category:'Home',name:'Monthly rent',date:demoDate(0,3)},
  {id:uid(),type:'expense',amount:3450,category:'Food & drinks',name:'Groceries',date:demoDate(0,5)},
  {id:uid(),type:'expense',amount:1250,category:'Transport',name:'Metro & cabs',date:demoDate(0,8)},
  {id:uid(),type:'expense',amount:2200,category:'Shopping',name:'Everyday essentials',date:demoDate(0,11)},
  {id:uid(),type:'income',amount:12000,category:'Freelance',name:'Design project',date:demoDate(0,14)},
  {id:uid(),type:'expense',amount:890,category:'Food & drinks',name:'Coffee & lunch',date:demoDate(0,16)},
  {id:uid(),type:'expense',amount:1600,category:'Bills',name:'Internet & phone',date:demoDate(0,20)},
  ...[1,2,3,4,5].flatMap((m)=>[
    {id:uid(),type:'income',amount:80000-m*1800,category:'Salary',name:'Monthly salary',date:demoDate(m,2)},
    {id:uid(),type:'expense',amount:25000+m*1100,category:'Home',name:'Monthly expenses',date:demoDate(m,8)},
    {id:uid(),type:'expense',amount:8500+m*450,category:'Food & drinks',name:'Food & groceries',date:demoDate(m,15)}
  ])],goals:[{id:uid(),name:'Emergency fund',target:100000,saved:37500,icon:'✦'},{id:uid(),name:'Weekend getaway',target:30000,saved:18600,icon:'✈'}],limits:[{id:uid(),category:'Food & drinks',amount:6000},{id:uid(),category:'Shopping',amount:5000},{id:uid(),category:'Transport',amount:3000}]};}
function load(){return {demo:false,transactions:[],goals:[],limits:[],customCategories:[]}}
let state=load(),view='home',filter='all',importRows=[],demoSession=false,currentUser=null,saveQueue=Promise.resolve(),lastSaveError=null;
if(!Array.isArray(state.customCategories))state.customCategories=[];
for(const category of state.customCategories)if(!CATEGORIES.includes(category))CATEGORIES.push(category);
function save(){state.demo=false;const snapshot=JSON.stringify(state);render();saveQueue=saveQueue.then(()=>api('/api/state',{method:'PUT',body:snapshot})).then(()=>{lastSaveError=null}).catch(err=>{lastSaveError=err;showToast('Could not save: '+err.message)});return saveQueue}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),3200)}
function monthlyTotals(key=thisMonth()){return state.transactions.filter(t=>monthKey(t.date)===key).reduce((a,t)=>(a[t.type]+=Number(t.amount),a),{income:0,expense:0})}
function categorySpent(cat,key=thisMonth()){return state.transactions.filter(t=>t.type==='expense'&&t.category===cat&&monthKey(t.date)===key).reduce((n,t)=>n+Number(t.amount),0)}
function statusFor(limit){let spent=categorySpent(limit.category),pct=spent/Number(limit.amount||1);return {spent,pct,label:pct>=1?'Limit reached':pct>=.8?'Getting close':'On track',cls:pct>=1?'over':pct>=.8?'warn':''}}
function sortedTransactions(){return [...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)||String(b.id).localeCompare(String(a.id)))}
function render(){const now=new Date(),tot=monthlyTotals(),balance=state.transactions.reduce((n,t)=>n+(t.type==='income'?1:-1)*Number(t.amount),0);$('#demo-banner').hidden=!state.demo;$('#today-label').textContent=now.toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'});$('#day-part').textContent=now.getHours()<12?'morning':now.getHours()<17?'afternoon':'evening';$('#balance-total').textContent=money(balance);$('#balance-caption').textContent=state.demo?'Sample data · income minus expenses':'Income minus expenses, all time';$('#month-income').textContent=money(tot.income);$('#month-expense').textContent=money(tot.expense);$('#expense-foot').textContent=tot.income?Math.round(tot.expense/tot.income*100)+'% of this month’s income':'Money going out';$('#spend-month-label').textContent=now.toLocaleDateString('en-IN',{month:'long',year:'numeric'});renderChart();renderBreakdown();renderTransactions();renderGoals();renderLimits();let alerts=state.limits.filter(l=>statusFor(l).pct>=.8).length;$('#notification-dot').style.display=alerts?'block':'none'}
function renderChart(){let max=0,data=[];for(let i=5;i>=0;i--){let d=new Date();d.setDate(1);d.setMonth(d.getMonth()-i);let key=localDate(d).slice(0,7),v=monthlyTotals(key);max=Math.max(max,v.income,v.expense);data.push({label:d.toLocaleDateString('en-IN',{month:'short'}),...v})}$('#cash-chart').innerHTML=data.map(d=>`<div class="bar-group"><div class="bar-pair"><div class="bar income" style="height:${max?Math.max(1,d.income/max*100):0}%" title="Income ${exactMoney(d.income)}"></div><div class="bar expense" style="height:${max?Math.max(1,d.expense/max*100):0}%" title="Expenses ${exactMoney(d.expense)}"></div></div><span>${d.label}</span></div>`).join('')}
function renderBreakdown(){let totals=new Map();state.transactions.filter(t=>t.type==='expense'&&monthKey(t.date)===thisMonth()).forEach(t=>totals.set(t.category,(totals.get(t.category)||0)+Number(t.amount)));let entries=[...totals].sort((a,b)=>b[1]-a[1]),sum=entries.reduce((n,e)=>n+e[1],0);$('#donut-total').textContent=money(sum);let angle=0;let stops=entries.map(([_,n],i)=>{let start=angle;angle+=n/sum*100;return `${COLORS[i%COLORS.length]} ${start}% ${angle}%`});$('#spend-donut').style.background=sum?`conic-gradient(${stops.join(',')})`:'#edf1ee';$('#category-legend').innerHTML=entries.length?entries.slice(0,6).map(([cat,n],i)=>`<div class="legend-row"><i style="background:${COLORS[i%COLORS.length]}"></i><span>${esc(cat)}</span><strong>${Math.round(n/sum*100)}%</strong></div>`).join(''):'<span class="helper">No expenses this month yet.</span>'}
function rowHTML(t,canDelete=false){return `<div class="transaction-row"><div class="transaction-icon ${t.type}">${esc(ICONS[t.category]||'◌')}</div><div class="transaction-meta"><strong>${esc(t.name)}</strong><small>${esc(t.category)} · ${niceDate(t.date)}</small></div><span class="transaction-amount ${t.type}">${t.type==='income'?'+':'−'}${money(t.amount)}</span>${canDelete?`<button class="row-delete" data-delete-transaction="${esc(t.id)}" aria-label="Delete ${esc(t.name)}">×</button>`:''}</div>`}
function renderTransactions(){let all=sortedTransactions();$('#recent-list').innerHTML=all.length?all.slice(0,4).map(t=>rowHTML(t)).join(''):'<div class="empty-state"><strong>No activity yet</strong>Add your first transaction to get started.</div>';let list=all.filter(t=>filter==='all'||t.type===filter),last='';$('#activity-list').innerHTML=list.length?list.map(t=>{let key=monthKey(t.date),heading=key!==last?`<div class="activity-date">${new Date(t.date+'T12:00:00').toLocaleDateString('en-IN',{month:'long',year:'numeric'}).toUpperCase()}</div>`:'';last=key;return heading+rowHTML(t,true)}).join(''):'<div class="empty-state"><strong>Nothing here yet</strong>Try another filter or add a transaction.</div>'}
function renderGoals(){let total=state.goals.reduce((n,g)=>n+Number(g.saved),0);$('#goals-saved').textContent=money(total);$('#home-goals').innerHTML=state.goals.length?state.goals.slice(0,2).map(g=>`<div class="goal-mini"><div class="goal-mini-top"><strong>${esc(g.icon||'◎')} ${esc(g.name)}</strong><span>${Math.round(g.saved/g.target*100)}%</span></div><div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,g.saved/g.target*100)}%"></div></div><small>${money(g.saved)} of ${money(g.target)}</small></div>`).join(''):'<div class="empty-state"><strong>No goals yet</strong>Create a savings goal and track your progress.</div>';$('#goals-grid').innerHTML=state.goals.length?state.goals.map(g=>`<div class="goal-card"><div class="goal-card-icon">${esc(g.icon||'◎')}</div><h3>${esc(g.name)}</h3><p>${g.saved>=g.target?'Goal reached!':'Keep going — you’ve got this.'}</p><div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,g.saved/g.target*100)}%"></div></div><div class="goal-card-bottom"><strong>${money(g.saved)} saved</strong><span>of ${money(g.target)}</span></div><div class="goal-card-actions"><button data-add-savings="${esc(g.id)}">＋ Add savings</button><button data-delete-goal="${esc(g.id)}">Delete</button></div></div>`).join(''):'<div class="panel empty-state"><strong>No goals yet</strong>Create a goal for something you care about.</div>'}
function renderLimits(){$('#limits-list').innerHTML=state.limits.length?state.limits.map(l=>{let s=statusFor(l);return `<div class="limit-card"><div class="limit-top"><div class="limit-icon">${esc(ICONS[l.category]||'◌')}</div><strong>${esc(l.category)}</strong><div class="limit-actions"><button data-edit-limit="${esc(l.id)}">Edit</button><button data-delete-limit="${esc(l.id)}">×</button></div></div><p><strong>${money(s.spent)}</strong> of ${money(l.amount)} this month</p><div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,s.pct*100)}%;background:${s.cls==='over'?'#dc806d':s.cls==='warn'?'#e4b16a':'#a9d66d'}"></div></div><div class="limit-bottom"><span>${Math.round(s.pct*100)}% used</span><span class="limit-status ${s.cls}">${s.label}</span></div></div>`}).join(''):'<div class="panel empty-state"><strong>No limits yet</strong>Set a monthly limit for any expense category.</div>'}
function navigate(next){view=next;$$('.view').forEach(el=>el.classList.toggle('active',el.id==='view-'+next));$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===next));$('#breadcrumb').textContent=({home:'Overview',activity:'Activity',goals:'Savings goals',limits:'Spending limits',insights:'AI insights',reports:'Reports'})[next];window.scrollTo({top:0,behavior:'smooth'})}
function openModal(type,options={}){const back=$('#modal-backdrop'),body=$('#modal-body');back.hidden=false;document.body.style.overflow='hidden';let title='',kicker='';if(type==='transaction'){title='Add transaction';kicker='KEEP TRACK';body.innerHTML=`<form id="transaction-form"><div class="type-picker"><label><input type="radio" name="type" value="expense" ${options.type==='income'?'':'checked'}><span>↗ Expense</span></label><label><input type="radio" name="type" value="income" ${options.type==='income'?'checked':''}><span>↙ Income</span></label></div><div class="field"><label for="tx-name">Description</label><input id="tx-name" name="name" placeholder="What was it for?" required maxlength="80" value="${esc(options.name||'')}"></div><div class="form-grid"><div class="field"><label for="tx-amount">Amount (₹)</label><input id="tx-amount" name="amount" type="number" min="0.01" step="0.01" placeholder="0.00" required value="${esc(options.amount||'')}"></div><div class="field"><label for="tx-date">Date</label><input id="tx-date" name="date" type="date" required value="${esc(options.date||today())}"></div></div><div class="field"><label for="tx-category">Category</label><select id="tx-category" name="category"></select></div><button class="button primary modal-submit" type="submit">Save transaction</button></form>`;updateCategorySelect(options.category);body.querySelectorAll('[name=type]').forEach(r=>r.addEventListener('change',()=>updateCategorySelect()));body.querySelector('form').addEventListener('submit',saveTransaction)}
else if(type==='goal'){title='New savings goal';kicker='SAVE FOR SOMETHING';body.innerHTML=`<form id="goal-form"><div class="field"><label>Goal name</label><input name="name" required maxlength="60" placeholder="e.g. New laptop"></div><div class="form-grid"><div class="field"><label>Target amount (₹)</label><input name="target" type="number" min="1" step="0.01" required placeholder="50000"></div><div class="field"><label>Already saved (₹)</label><input name="saved" type="number" min="0" step="0.01" value="0" required></div></div><div class="field"><label>Choose an icon</label><select name="icon"><option>✦</option><option>✈</option><option>⌂</option><option>◈</option><option>♡</option><option>◎</option></select></div><button class="button primary modal-submit">Create goal</button></form>`;body.querySelector('form').addEventListener('submit',saveGoal)}
else if(type==='savings'){let g=state.goals.find(g=>g.id===options.id);if(!g)return;title='Add savings';kicker=esc(g.name);body.innerHTML=`<form id="savings-form"><p class="helper">${money(g.saved)} saved toward ${money(g.target)}.</p><div class="field"><label>Amount to add (₹)</label><input name="amount" type="number" min="0.01" step="0.01" required autofocus></div><button class="button primary modal-submit">Add to goal</button></form>`;body.querySelector('form').addEventListener('submit',e=>{e.preventDefault();let a=Number(new FormData(e.target).get('amount'));if(!(a>0))return;g.saved+=a;state.demo=false;save();closeModal();showToast('Savings added to your goal')})}
else if(type==='limit'){let l=state.limits.find(l=>l.id===options.id);title=l?'Edit spending limit':'Set a spending limit';kicker='A MONTHLY BOUNDARY';body.innerHTML=`<form id="limit-form"><div class="field"><label>Expense category</label><select name="category">${CATEGORIES.map(c=>`<option ${l?.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="field"><label>Monthly limit (₹)</label><input name="amount" type="number" min="1" step="0.01" required placeholder="5000" value="${l?.amount||''}"></div><p class="helper">You’ll see an alert when spending reaches 80% and 100% of this amount.</p><button class="button primary modal-submit">${l?'Save changes':'Set limit'}</button></form>`;body.querySelector('form').addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target),cat=f.get('category'),amount=Number(f.get('amount'));if(!(amount>0))return;let existing=state.limits.find(x=>x.category===cat&&x.id!==l?.id);if(existing){showToast('A limit already exists for this category');return}if(l){l.category=cat;l.amount=amount}else state.limits.push({id:uid(),category:cat,amount});state.demo=false;save();closeModal();showToast('Spending limit saved')})}
else if(type==='import'){title='Import statement';kicker='BRING YOUR DATA IN';body.innerHTML=`<p class="helper">Choose a CSV bank statement. We’ll preview the entries before adding them. Dates, descriptions, and either amount or debit/credit columns are supported.</p><div class="file-zone" id="select-csv"><span class="file-icon">⇧</span><strong>Choose a CSV file</strong><p>Tap to browse your files</p></div><div class="import-preview" id="import-preview"></div><button class="button primary modal-submit" id="confirm-import" disabled>Import transactions</button>`;$('#select-csv').onclick=()=>$('#csv-input').click();$('#confirm-import').onclick=confirmImport}
else if(type==='photo'){title='Scan a receipt';kicker='ADD FROM A PHOTO';body.innerHTML=`<p class="helper">Take or choose a clear photo. Text recognition runs in your browser. Review the detected details before saving.</p><div class="file-zone" id="select-photo"><span class="file-icon">▧</span><strong>Choose or take a photo</strong><p>JPG, PNG, or camera capture</p></div><div id="scan-result"></div>`;$('#select-photo').onclick=()=>$('#photo-input').click()}
else if(type==='notifications'){title='Notifications';kicker='SPENDING CHECK-IN';let alerts=state.limits.map(l=>({l,...statusFor(l)})).filter(x=>x.pct>=.8);body.innerHTML=alerts.length?alerts.map(a=>`<div class="transaction-row"><div class="transaction-icon expense">!</div><div class="transaction-meta"><strong>${esc(a.l.category)}: ${a.label.toLowerCase()}</strong><small>${money(a.spent)} of ${money(a.l.amount)} monthly limit</small></div></div>`).join(''):'<div class="empty-state"><strong>All clear</strong>No category is close to its monthly limit.</div>';if('Notification' in window&&Notification.permission==='default')body.innerHTML+='<button class="button secondary modal-submit" id="enable-browser-alerts">Enable browser alerts</button>';let b=$('#enable-browser-alerts');if(b)b.onclick=async()=>{let p=await Notification.requestPermission();b.remove();showToast(p==='granted'?'Browser alerts enabled':'You can still see alerts here')}}
else if(type==='profile'){title='My account';kicker='FINWISE';body.innerHTML=`<p class="helper">Signed in as <strong>${esc(currentUser?.email||'')}</strong>. Your records are saved privately in this computer’s Finwise database.</p><div class="field"><label>Transactions</label><input disabled value="${state.transactions.length} saved"></div><button class="button secondary modal-submit" id="sign-out">Sign out</button><button class="button secondary modal-submit" id="clear-data">Clear my financial records</button>`;$('#sign-out').onclick=signOut;$('#clear-data').onclick=async()=>{if(!confirm('Permanently delete all transactions, goals, and limits for this account?'))return;state=load();CATEGORIES.splice(5);await save();if(lastSaveError)return;closeModal();showToast('Financial records cleared')}}
$('#modal-kicker').textContent=kicker;$('#modal-title').textContent=title;setTimeout(()=>body.querySelector('input:not([type=radio]),select,button')?.focus(),50)}
function closeModal(){$('#modal-backdrop').hidden=true;document.body.style.overflow=''}
function updateCategorySelect(selected){let type=document.querySelector('[name=type]:checked')?.value||'expense',sel=$('#tx-category');if(!sel)return;sel.innerHTML=(type==='income'?INCOME_CATEGORIES:CATEGORIES).map(c=>`<option ${selected===c?'selected':''}>${esc(c)}</option>`).join('')+(type==='expense'?'<option value="__new__">＋ Add a category…</option>':'');sel.onchange=()=>{if(sel.value!=='__new__')return;let name=prompt('Name your new expense category:')?.trim();if(!name){sel.value=CATEGORIES[0];return}if(CATEGORIES.some(c=>c.toLowerCase()===name.toLowerCase())){showToast('That category already exists');sel.value=CATEGORIES[0];return}CATEGORIES.push(name.slice(0,40));state.customCategories.push(name.slice(0,40));save();updateCategorySelect(name.slice(0,40));showToast('Category added')}}
function maybeNotify(previous){for(const l of state.limits){let before=previous[l.category]||0,after=statusFor(l).pct;if((before<.8&&after>=.8)||(before<1&&after>=1)){let msg=`${l.category} is ${after>=1?'at or over':'near'} its monthly limit.`;showToast(msg);if('Notification' in window&&Notification.permission==='granted')new Notification('Finwise spending alert',{body:msg})}}}
function saveTransaction(e){e.preventDefault();let f=new FormData(e.target),amount=Number(f.get('amount')),name=String(f.get('name')||'').trim(),date=f.get('date');if(!name||!(amount>0)||!parseDate(date))return;let prev=Object.fromEntries(state.limits.map(l=>[l.category,statusFor(l).pct]));state.transactions.push({id:uid(),type:f.get('type'),amount,category:f.get('category'),name,date});state.demo=false;save();closeModal();showToast('Transaction saved');maybeNotify(prev)}
function saveGoal(e){e.preventDefault();let f=new FormData(e.target),target=Number(f.get('target')),saved=Number(f.get('saved'));if(!(target>0)||saved<0)return;state.goals.push({id:uid(),name:String(f.get('name')).trim(),target,saved,icon:f.get('icon')});state.demo=false;save();closeModal();showToast('Goal created')}
function csvRows(text){let out=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))out.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))out.push(row);return out}
function numberFrom(s){let v=String(s??'').replace(/[₹,$\s]/g,'').replace(/\((.*)\)/,'-$1');let n=Number(v);return Number.isFinite(n)?n:0}
function parseStatement(text){let rows=csvRows(text.replace(/^\uFEFF/,''));if(rows.length<2)throw Error('The CSV has no transaction rows.');let h=rows[0].map(x=>x.trim().toLowerCase());let col=(...keys)=>h.findIndex(x=>keys.some(k=>x===k||x.includes(k)));let date=col('transaction date','value date','posting date','date'),name=col('description','narration','merchant','details','particulars','memo'),amount=col('transaction amount','amount','amt'),debit=col('debit','withdrawal','money out'),credit=col('credit','deposit','money in'),kind=col('type','dr/cr');if(date<0||name<0||(amount<0&&debit<0&&credit<0))throw Error('Could not find date, description, and amount columns.');let data=[];for(const row of rows.slice(1)){let d=parseDate(row[date]),label=String(row[name]||'').trim();if(!d||!label)continue;let cr=credit>=0?numberFrom(row[credit]):0,dr=debit>=0?numberFrom(row[debit]):0,raw=amount>=0?numberFrom(row[amount]):0;let value=cr||dr||Math.abs(raw);if(!(value>0))continue;let type=cr?'income':dr?'expense':raw<0?'expense':/credit|\bcr\b|deposit|income/i.test(String(row[kind]||''))?'income':'expense';data.push({id:uid(),date:d,name:label.slice(0,80),amount:value,type,category:type==='income'?'Other income':'Other'})}if(!data.length)throw Error('No valid transactions were found.');return data}
async function onCsvFile(e){let file=e.target.files?.[0];if(!file)return;try{importRows=parseStatement(await file.text());$('#import-preview').innerHTML=`<strong>${importRows.length} transactions found</strong>`+importRows.slice(0,5).map(r=>`<div>${niceDate(r.date)} · ${esc(r.name)} · ${r.type==='income'?'+':'−'}${money(r.amount)}</div>`).join('')+'<p>Imported expenses use “Other” and income uses “Other income”. You can adjust categories by adding entries manually.</p>';$('#confirm-import').disabled=false}catch(err){importRows=[];$('#import-preview').textContent=err.message;$('#confirm-import').disabled=true}e.target.value=''}
function confirmImport(){let seen=new Set(state.transactions.map(t=>`${t.date}|${t.name.toLowerCase()}|${t.amount}|${t.type}`)),added=0,prev=Object.fromEntries(state.limits.map(l=>[l.category,statusFor(l).pct]));for(let r of importRows){let key=`${r.date}|${r.name.toLowerCase()}|${r.amount}|${r.type}`;if(!seen.has(key)){state.transactions.push(r);seen.add(key);added++}}if(added){state.demo=false;save();maybeNotify(prev)}closeModal();showToast(`${added} transaction${added===1?'':'s'} imported`);importRows=[]}
async function onPhotoFile(e){let file=e.target.files?.[0];if(!file)return;let result=$('#scan-result');if(!result)return;let url=URL.createObjectURL(file);result.innerHTML=`<img class="image-preview" alt="Selected receipt" src="${url}"><p class="scan-status">Loading text recognition…</p>`;try{if(!window.Tesseract){await new Promise((resolve,reject)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}result.querySelector('.scan-status').textContent='Reading photo…';let r=await Tesseract.recognize(file,'eng');let text=r.data.text||'',lines=text.split('\n').map(x=>x.trim()).filter(Boolean);let numbers=[...text.matchAll(/(?:₹|Rs\.?|INR)?\s*(\d{1,3}(?:,\d{3})*(?:\.\d{2})|\d+\.\d{2})/gi)].map(m=>numberFrom(m[1])).filter(n=>n>0&&n<10000000);let totalLine=lines.find(l=>/grand total|amount paid|total due|total\s*[:₹]/i.test(l));let totalMatch=totalLine?.match(/([\d,]+(?:\.\d{2})?)(?!.*\d)/);let amount=totalMatch?numberFrom(totalMatch[1]):Math.max(...numbers,0);let label=lines.find(l=>/[a-zA-Z]{3}/.test(l)&&!/tax invoice|receipt|total/i.test(l))||'Receipt';result.innerHTML=`<p class="scan-status">Text found. Please check the details before saving.</p><div class="import-preview">${esc(text.slice(0,450))}</div><button class="button primary modal-submit" id="use-scan">Review transaction →</button>`;$('#use-scan').onclick=()=>openModal('transaction',{name:label.slice(0,80),amount:amount||''})}catch{result.innerHTML='<p class="scan-status">Could not read this photo. Text recognition needs an internet connection the first time. You can add the transaction manually.</p><button class="button primary modal-submit" id="manual-from-photo">Add manually →</button>';$('#manual-from-photo').onclick=()=>openModal('transaction')}finally{URL.revokeObjectURL(url);e.target.value=''}}
function download(name,content,type){let blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000)}
function exportCSV(){let q=s=>'"'+String(s??'').replace(/"/g,'""')+'"';let rows=[['Date','Type','Description','Category','Amount (INR)'],...sortedTransactions().map(t=>[t.date,t.type,t.name,t.category,t.amount])];download(`finwise-transactions-${today()}.csv`,rows.map(r=>r.map(q).join(',')).join('\r\n'),'text/csv;charset=utf-8');showToast('Transactions downloaded')}
function downloadReport(){let key=thisMonth(),tot=monthlyTotals(),month=new Date().toLocaleDateString('en-IN',{month:'long',year:'numeric'}),cat=[...new Set(state.transactions.filter(t=>t.type==='expense'&&monthKey(t.date)===key).map(t=>t.category))].map(c=>[c,categorySpent(c)]).sort((a,b)=>b[1]-a[1]);let rows=sortedTransactions().filter(t=>monthKey(t.date)===key).map(t=>`<tr><td>${esc(niceDate(t.date))}</td><td>${esc(t.name)}</td><td>${esc(t.category)}</td><td>${t.type==='income'?'+':'−'}${exactMoney(t.amount)}</td></tr>`).join('');let html=`<!doctype html><html><head><meta charset="utf-8"><title>Finwise report — ${esc(month)}</title><style>body{font:14px Arial,sans-serif;color:#20352b;max-width:820px;margin:40px auto;padding:0 24px}header{border-bottom:3px solid #a9d66d;padding-bottom:18px}h1{font-size:30px;margin:7px 0}h2{font-size:18px;margin-top:35px}.small{color:#7c8f82}.summary{display:flex;gap:12px;margin:25px 0}.summary div{flex:1;background:#eff5e9;padding:16px;border-radius:9px}.summary strong{display:block;font-size:20px;margin-top:6px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{text-align:left;padding:10px 7px;border-bottom:1px solid #e5ece6}th{background:#f4f8f2}.print{padding:10px 16px;background:#203b2c;color:white;border:0;border-radius:6px;cursor:pointer}@media print{.print{display:none}body{margin:0}}</style></head><body><header><div class="small">FINWISE / MONTHLY REPORT</div><h1>${esc(month)}</h1><div class="small">Generated ${esc(niceDate(today()))}</div></header><div class="summary"><div>Income<strong>${exactMoney(tot.income)}</strong></div><div>Expenses<strong>${exactMoney(tot.expense)}</strong></div><div>Net<strong>${exactMoney(tot.income-tot.expense)}</strong></div></div><h2>Spending by category</h2><table><thead><tr><th>Category</th><th>Amount</th></tr></thead><tbody>${cat.map(([c,n])=>`<tr><td>${esc(c)}</td><td>${exactMoney(n)}</td></tr>`).join('')||'<tr><td colspan="2">No expenses this month</td></tr>'}</tbody></table><h2>Savings goals</h2><table><thead><tr><th>Goal</th><th>Saved</th><th>Target</th></tr></thead><tbody>${state.goals.map(g=>`<tr><td>${esc(g.name)}</td><td>${exactMoney(g.saved)}</td><td>${exactMoney(g.target)}</td></tr>`).join('')||'<tr><td colspan="3">No goals yet</td></tr>'}</tbody></table><h2>Transactions</h2><table><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Amount</th></tr></thead><tbody>${rows||'<tr><td colspan="4">No transactions this month</td></tr>'}</tbody></table><p style="margin-top:35px"><button class="print" onclick="print()">Print / Save as PDF</button></p></body></html>`;download(`finwise-report-${key}.html`,html,'text/html;charset=utf-8');showToast('Monthly report downloaded')}
document.addEventListener('click',e=>{let v=e.target.closest('[data-view]');if(v){navigate(v.dataset.view);return}let o=e.target.closest('[data-open]');if(o){openModal(o.dataset.open);return}let d=e.target.closest('[data-delete-transaction]');if(d){if(!confirm('Delete this transaction?'))return;state.transactions=state.transactions.filter(t=>t.id!==d.dataset.deleteTransaction);state.demo=false;save();showToast('Transaction deleted');return}let g=e.target.closest('[data-add-savings]');if(g){openModal('savings',{id:g.dataset.addSavings});return}let gd=e.target.closest('[data-delete-goal]');if(gd){if(!confirm('Delete this savings goal?'))return;state.goals=state.goals.filter(x=>x.id!==gd.dataset.deleteGoal);state.demo=false;save();showToast('Goal deleted');return}let le=e.target.closest('[data-edit-limit]');if(le){openModal('limit',{id:le.dataset.editLimit});return}let ld=e.target.closest('[data-delete-limit]');if(ld){if(!confirm('Delete this spending limit?'))return;state.limits=state.limits.filter(x=>x.id!==ld.dataset.deleteLimit);state.demo=false;save();showToast('Limit deleted')}});
$('#activity-filter').addEventListener('click',e=>{let b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;$$('#activity-filter button').forEach(x=>x.classList.toggle('selected',x===b));renderTransactions()});$('#close-modal').onclick=closeModal;$('#modal-backdrop').addEventListener('click',e=>{if(e.target.id==='modal-backdrop')closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal-backdrop').hidden)closeModal()});$('#csv-input').addEventListener('change',onCsvFile);$('#photo-input').addEventListener('change',onPhotoFile);$('#notification-btn').onclick=()=>openModal('notifications');$('#profile-btn').onclick=()=>openModal('profile');$('#export-csv').onclick=exportCSV;$('#download-report').onclick=downloadReport;
async function api(path,options={}){let headers={...(options.headers||{})};if(options.method&&options.method!=='GET'){headers['X-Finwise-Request']='1';headers['Content-Type']='application/json'}let response=await fetch(path,{credentials:'same-origin',...options,headers});let data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||`Request failed (${response.status})`);return data}
let registerMode=false;
function showAuth(message=''){if(registerMode)toggleAuth();currentUser=null;$('#app').hidden=true;$('#auth-screen').hidden=false;$('#auth-error').textContent=message;$('#auth-password').value=''}
function showApp(user,stored){currentUser=user;state=stored;state.customCategories=Array.isArray(state.customCategories)?state.customCategories:[];CATEGORIES.splice(5);for(const c of state.customCategories)if(!CATEGORIES.includes(c))CATEGORIES.push(c);$('#auth-screen').hidden=true;$('#app').hidden=false;$$('.sidebar-profile .avatar,.top-avatar,#mobile-profile-btn').forEach(el=>el.textContent=(user.displayName||'FW').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase());$('.sidebar-profile strong').textContent=user.displayName;render();navigate('home')}
async function bootstrap(){try{let user=await api('/api/me');let stored=await api('/api/state');showApp(user,stored.state)}catch(err){showAuth(err.message==='Please sign in.'?'':err.message)}}
function toggleAuth(){registerMode=!registerMode;$('#auth-title').innerHTML=registerMode?'Create your account<span class="heading-dot">.</span>':'Welcome back<span class="heading-dot">.</span>';$('#auth-subtitle').textContent=registerMode?'A private space for your money.':'Sign in to see your finances.';$('#auth-name-field').hidden=!registerMode;$('#auth-name').required=registerMode;$('#auth-password').autocomplete=registerMode?'new-password':'current-password';$('#auth-submit').textContent=registerMode?'Create account':'Sign in';$('#auth-switch-text').textContent=registerMode?'Already have an account?':'New to Finwise?';$('#auth-switch-button').textContent=registerMode?'Sign in':'Create an account';$('#auth-error').textContent=''}
async function signOut(){await saveQueue;if(lastSaveError){showToast('Save failed. Stay signed in and try again.');return}try{await api('/api/logout',{method:'POST',body:'{}'});closeModal();state=load();showAuth();showToast('Signed out')}catch(err){showToast(err.message)}}
async function analyze(){const button=$('#analyze-button'),results=$('#insight-results');if(!state.transactions.length){showToast('Add a transaction first');return}button.disabled=true;button.textContent='Analyzing…';results.innerHTML='<div class="panel empty-state"><strong>Looking at your numbers…</strong>This may take a minute.</div>';try{await saveQueue;if(lastSaveError)throw Error('Save your latest changes before analyzing.');let data=await api('/api/ai/insights',{method:'POST',body:'{}'}),v=data.insights;results.innerHTML=`<div class="panel insight-summary"><span class="eyebrow accent">YOUR MONEY AT A GLANCE</span><h2>${esc(v.summary)}</h2><p>${esc(v.outlook)}</p></div><div class="insight-columns"><div class="panel"><span class="eyebrow accent">WHAT STANDS OUT</span><ul>${v.observations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="panel"><span class="eyebrow accent">IDEAS TO TRY</span><ul>${v.suggestions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div>`}catch(err){results.innerHTML=`<div class="panel empty-state"><strong>Analysis unavailable</strong>${esc(err.message)}</div>`}finally{button.disabled=false;button.textContent='✦ Analyze my finances'}}
$('#auth-switch-button').onclick=toggleAuth;
$('#auth-form').addEventListener('submit',async e=>{e.preventDefault();let button=$('#auth-submit');button.disabled=true;$('#auth-error').textContent='';try{let f=new FormData(e.target),wasRegister=registerMode,body={email:f.get('email'),password:f.get('password'),displayName:f.get('displayName')};let user=await api(registerMode?'/api/register':'/api/login',{method:'POST',body:JSON.stringify(body)}),stored=await api('/api/state');let old;try{old=JSON.parse(localStorage.getItem(STORE))}catch{}if(old&&!old.demo&&Array.isArray(old.transactions)&&Array.isArray(old.goals)&&Array.isArray(old.limits)&&(old.transactions.length||old.goals.length||old.limits.length)&&confirm('Import financial records from the earlier browser-only version into this account?')){old.customCategories=Array.isArray(old.customCategories)?old.customCategories:[];await api('/api/state',{method:'PUT',body:JSON.stringify(old)});stored.state=old;localStorage.removeItem(STORE)}showApp(user,stored.state);showToast(wasRegister?'Account created':'Welcome back')}catch(err){$('#auth-error').textContent=err.message}finally{button.disabled=false}});
$('#analyze-button').onclick=analyze;
$('#splash-tip').textContent=TIPS[Math.floor(Math.random()*TIPS.length)];render();bootstrap();setTimeout(()=>$('#splash').classList.add('hide'),1350);
$('#start-workspace').onclick=()=>{};
$('#mobile-profile-btn').onclick=()=>openModal('profile');
